"""notification

Revision ID: 5ffc48f71ba2
Revises: 7126204933b5
Create Date: 2023-04-10 14:12:29.285143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ffc48f71ba2'
down_revision = '7126204933b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('notification_token', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'server_resource', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'server_resource', type_='unique')
    op.drop_column('device', 'notification_token')
    # ### end Alembic commands ###
