version: "3.9"

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    hostname: ${APP_HOST}

  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ${STORE_DIR}/db:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    hostname: ${POSTGRES_HOST}
    restart: always
