version: "3.9"

services:
  app:
    container_name: app
    build: .
    env_file:
      - .env
    volumes:
      - ./app:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always
    networks:
      net:
        aliases:
          - ${APP_HOST}

  db:
    container_name: db
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DIR}/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    networks:
      net:
        aliases:
          - ${POSTGRES_HOST}

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: always
    networks:
      net:
        aliases:
          - ${REDIS_HOST}

networks:
  net:
    driver: bridge
