pipeline {
    agent any
    options {
        buildDiscarder(logRotator(numToKeepStr: '4', artifactNumToKeepStr: '4'))
        disableConcurrentBuilds(abortPrevious: true)
    }
    parameters {
        string( name: 'host', defaultValue: "95.163.235.179", description: 'Адрес сервера')
    }
    stages {
        stage('Тест соединения') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'repozitarium', keyFileVariable: 'sshKey')]) {
                    script {
                        def result = sh returnStdout: true, script:'ssh -i ${sshKey} root@${host} -C "echo \\$HOME"'
                        echo result
                    }
                }
            }
        }
        stage('Копирование проекта') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'repozitarium', keyFileVariable: 'sshKey')]) {
                    script {
                        sh 'scp -i ${sshKey} -rp ${WORKSPACE} root@${host}:/app'
                    }
                }
            }
        }
    }
}